### ISSUE TITLE
Encoding hardcoded to Windows-1252

### ISSUE THREAD

**Issue by froque** [SolRIA/saft-pt#1]
https://github.com/SolRIA/saft-pt/blob/8166a15e309923d18e9e7398a8d5cff649cee784/src/Solria.SAFT.Desktop/Solria.SAFT.Desktop/Services/XmlSerializer.cs#L17

This doesn't allow to open a XML file encoded with UTF-8.

**Comment by fredericoregateiro** [comment]
Yes your right, that code was made to read our generated SAFT files.
That code needs rework to check the file encoding.

**Comment by fredericoregateiro** [comment]
The encoding is not hard coded in the new parser 04fe21730a83cba682f1c6707773f214f4fa1601
