### ISSUE TITLE
How to compile this repo

### ISSUE THREAD

**Issue by Justinas-Jurciukonis** [SolRIA/saft-pt#2]
Hello, can you provide description how to compile this repo on Mac?

I have installed [Mono](https://www.mono-project.com/docs/about-mono/supported-platforms/macos/) and tried to execute ` csc src/Solria.SAFT.Desktop/ConsoleApp/Program.cs` but got error that `The type or namespace name 'Spectre' could not be found`
<img width="921" alt="Screenshot 2022-07-29 at 11 30 17" src="https://user-images.githubusercontent.com/33222536/181718441-572a509a-556d-4457-b2d6-9f330eadfcfa.png">

**Comment by fredericoregateiro** [comment]
Hi @Justinas-Jurciukonis 
I never try to build it on a Mac and neither with mono.
All the projects are using the .net 6.0, with you can install on a mac and try to build with that version.

If the only error is on the console project, you can remove that project and try to build only the Avalonia and the Parser projects.
